### ISSUE TITLE
When execute a recurring job with multiple workers, the job will be executed many times.

### ISSUE THREAD

**Issue by zhangliuping** [gresrun/jesque#93] opened 2015-12-09 08:43 UTC
Hello,
   
I add several recurring job in a delayed queue, then run some workers, I found the job will be executed more than once. Then I look the code. I found the implementation on WorkerImpl#pop had concurrent 
problem. The recurring job always in queues and can be obtained by other woker. I know the zadd data structure has not pop method like LPOP.

That's all, please let me know how do you think.

**Comment by argvk** [comment] 2015-12-14 07:35
this is probably related to https://github.com/gresrun/jesque/issues/91

**Comment by zhangliuping** [comment] 2015-12-14 08:19
I fix this problem and rewrite the method WorkerImpl#pop as follow:

    @Override
    protected String pop(final String curQueue) {
        final String key = key(QUEUE, curQueue);
        String payload = null;
        double score = 0;
        // If a delayed queue, peek and remove from ZSET
        if (JedisUtils.isDelayedQueue(this.jedis, key)) {
            // Synchronized block to ensure the meet condition job can be peek and remove consistency from queues.
            synchronized (LOCK) {
                final long now = System.currentTimeMillis();
                // Peek ==> is there any item scheduled to run between -INF and now?
                final Set<Tuple> payloadSet = this.jedis.zrangeByScoreWithScores(key, -1, now, 0, 1);
                if (payloadSet != null && !payloadSet.isEmpty()) {
                    final Tuple tuple = payloadSet.iterator().next();
                    final String tmp = tuple.getElement();
                    score = tuple.getScore();
                    if (this.jedis.zrem(key, tmp) == 1) {
                        payload = tmp;
                    }
                }
            }
            if (payload != null) {
                String recurringHashKey = JesqueUtils.createRecurringHashKey(key);
                if (this.jedis.hexists(recurringHashKey, payload)) {
                    // Watch the hash to ensure that the job isn't deleted
                    // TODO: Use the ZADD XX feature
                    this.jedis.watch(recurringHashKey);
                    final Long frequency = Long.valueOf(this.jedis.hget(recurringHashKey, payload));
                    final Transaction transaction = this.jedis.multi();
                    transaction.zadd(key, score + frequency, payload);
                    if (transaction.exec() == null) {
                        payload = null;
                    }
                }
            }
        } else if (JedisUtils.isRegularQueue(this.jedis, key)) { // If a regular queue, pop from it
            payload = lpoplpush(key, key(INFLIGHT, getName(), curQueue));
        }
        return payload;
    }

**Comment by gresrun** [comment] 2015-12-14 14:14
I agree, I believe this is a duplicate of #91.

**Closed by gresrun** 2015-12-14 14:14 UTC
Labels: Bug
